using System;

namespace Exanite.Core.Numbers
{
    /// <summary>
    ///     Abbreviations of number names
    /// </summary>
    [Serializable]
    public enum NumScalesShort
    {
        // Scales found at https://en.wikipedia.org/wiki/Names_of_large_numbers

        None = 0,
        K = 1,
        M = 2,
        B = 3,
        T = 4,
        Qd = 5,
        Qn = 6,
        Sx = 7,
        Sp = 8,
        O = 9,
        N = 10,

        DE = 11,
        UD = 12,
        DD = 13,
        TD = 14,
        QdD = 15,
        QnD = 16,
        SxD = 17,
        SpD = 18,
        OcD = 19,
        NvD = 20,

        VGN = 21,
        UV = 22,
        DV = 23,
        TV = 24,
        QdV = 25,
        QnV = 26,
        SxV = 27,
        SpV = 28,
        OcV = 29,
        NvV = 30,

        TGN = 31,
        UT = 32,
        DT = 33,
        TT = 34,
        QdT = 35,
        QnT = 36,
        SxT = 37,
        SpT = 38,
        OcT = 39,
        NvT = 40,

        QDN = 41,
        UQd = 42,
        DQd = 43,
        TQd = 44,
        QdQd = 45,
        QnQd = 46,
        SxQd = 47,
        SpQd = 48,
        OcQd = 49,
        NvQd = 50,

        QNN = 51,
        UQn = 52,
        DQn = 53,
        TQn = 54,
        QdQn = 55,
        QnQn = 56,
        SxQn = 57,
        SpQn = 58,
        OcQn = 59,
        NvQn = 60,

        SXN = 61,
        USx = 62,
        DSx = 63,
        TSx = 64,
        QdSx = 65,
        QnSx = 66,
        SxSx = 67,
        SpSx = 68,
        OcSx = 69,
        NvSx = 70,

        SPN = 71,
        USp = 72,
        DSp = 73,
        TSp = 74,
        QdSp = 75,
        QnSp = 76,
        SxSp = 77,
        SpSp = 78,
        OcSp = 79,
        NvSp = 80,

        OCN = 81,
        UOc = 82,
        DOc = 83,
        TOc = 84,
        QdOc = 85,
        QnOc = 86,
        SxOc = 87,
        SpOc = 88,
        OcOc = 89,
        NvOc = 90,

        NGN = 91,
        UNg = 92,
        DNg = 93,
        TNg = 94,
        QdNg = 95,
        QnNg = 96,
        SxNg = 97,
        SpNg = 98,
        OcNg = 99,
        NvNg = 100,

        CE = 101,
    }
}