//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Project.Source/Input/AbilityInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Project.Source.Input
{
    public partial class @AbilityInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @AbilityInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""AbilityInputActions"",
    ""maps"": [
        {
            ""name"": ""PlayerAbilities"",
            ""id"": ""beda1f7d-3362-4779-b8c8-05f45bffcd70"",
            ""actions"": [
                {
                    ""name"": ""ExecuteAbility0"",
                    ""type"": ""Button"",
                    ""id"": ""93d0bfdf-4ea8-4b60-bbdd-a24608b28127"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExecuteAbility1"",
                    ""type"": ""Button"",
                    ""id"": ""31b1c8bd-625c-4029-89c9-e80997ae6a34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a58fd2ca-fddf-44ca-9f07-f618c89f6015"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExecuteAbility0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c460063-32ee-44c0-a774-9db4d79f35e0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExecuteAbility1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PlayerAbilities
            m_PlayerAbilities = asset.FindActionMap("PlayerAbilities", throwIfNotFound: true);
            m_PlayerAbilities_ExecuteAbility0 = m_PlayerAbilities.FindAction("ExecuteAbility0", throwIfNotFound: true);
            m_PlayerAbilities_ExecuteAbility1 = m_PlayerAbilities.FindAction("ExecuteAbility1", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PlayerAbilities
        private readonly InputActionMap m_PlayerAbilities;
        private IPlayerAbilitiesActions m_PlayerAbilitiesActionsCallbackInterface;
        private readonly InputAction m_PlayerAbilities_ExecuteAbility0;
        private readonly InputAction m_PlayerAbilities_ExecuteAbility1;
        public struct PlayerAbilitiesActions
        {
            private @AbilityInputActions m_Wrapper;
            public PlayerAbilitiesActions(@AbilityInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @ExecuteAbility0 => m_Wrapper.m_PlayerAbilities_ExecuteAbility0;
            public InputAction @ExecuteAbility1 => m_Wrapper.m_PlayerAbilities_ExecuteAbility1;
            public InputActionMap Get() { return m_Wrapper.m_PlayerAbilities; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerAbilitiesActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerAbilitiesActions instance)
            {
                if (m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface != null)
                {
                    @ExecuteAbility0.started -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnExecuteAbility0;
                    @ExecuteAbility0.performed -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnExecuteAbility0;
                    @ExecuteAbility0.canceled -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnExecuteAbility0;
                    @ExecuteAbility1.started -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnExecuteAbility1;
                    @ExecuteAbility1.performed -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnExecuteAbility1;
                    @ExecuteAbility1.canceled -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnExecuteAbility1;
                }
                m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ExecuteAbility0.started += instance.OnExecuteAbility0;
                    @ExecuteAbility0.performed += instance.OnExecuteAbility0;
                    @ExecuteAbility0.canceled += instance.OnExecuteAbility0;
                    @ExecuteAbility1.started += instance.OnExecuteAbility1;
                    @ExecuteAbility1.performed += instance.OnExecuteAbility1;
                    @ExecuteAbility1.canceled += instance.OnExecuteAbility1;
                }
            }
        }
        public PlayerAbilitiesActions @PlayerAbilities => new PlayerAbilitiesActions(this);
        public interface IPlayerAbilitiesActions
        {
            void OnExecuteAbility0(InputAction.CallbackContext context);
            void OnExecuteAbility1(InputAction.CallbackContext context);
        }
    }
}
